# Generated by Django 5.0.7 on 2024-08-07 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OttoInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_type', models.CharField(blank=True, max_length=100)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OttoImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('cap_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('robot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.robot')),
                ('otto_inference', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otto.ottoinference')),
            ],
        ),
    ]
